import request from '@/utils/request'

export const login = (data) => request.post('/auth/login', data)
export const register = (data) => request.post('/auth/register', data)
export const getUserInfo = () => request.get('/auth/info')
export const changePassword = (data) => request.put('/auth/password', data)
export const resetPassword = (data) => request.put('/auth/reset-password', data)

export const getDashboardStats = () => request.get('/dashboard/statistics')

export const getUsers = (params) => request.get('/users', { params })
export const getUser = (id) => request.get(`/users/${id}`)
export const createUser = (data) => request.post('/users', data)
export const updateUser = (id, data) => request.put(`/users/${id}`, data)
export const deleteUser = (id) => request.delete(`/users/${id}`)

export const getRoles = (params) => request.get('/roles', { params })
export const getAllRoles = () => request.get('/roles/all')
export const getRole = (id) => request.get(`/roles/${id}`)
export const createRole = (data) => request.post('/roles', data)
export const updateRole = (id, data) => request.put(`/roles/${id}`, data)
export const deleteRole = (id) => request.delete(`/roles/${id}`)

export const getModules = (params) => request.get('/modules', { params })
export const getModuleTree = () => request.get('/modules/tree')
export const getAllModules = () => request.get('/modules/all')
export const getModule = (id) => request.get(`/modules/${id}`)
export const createModule = (data) => request.post('/modules', data)
export const updateModule = (id, data) => request.put(`/modules/${id}`, data)
export const deleteModule = (id) => request.delete(`/modules/${id}`)

export const getDictionaries = (params) => request.get('/dictionaries', { params })
export const getDictionaryTypes = () => request.get('/dictionaries/types')
export const getDictionaryByType = (type) => request.get(`/dictionaries/type/${type}`)
export const getDictionary = (id) => request.get(`/dictionaries/${id}`)
export const createDictionary = (data) => request.post('/dictionaries', data)
export const updateDictionary = (id, data) => request.put(`/dictionaries/${id}`, data)
export const deleteDictionary = (id) => request.delete(`/dictionaries/${id}`)

export const getLoginLogs = (params) => request.get('/logs/login', { params })
export const getOperationLogs = (params) => request.get('/logs/operation', { params })

export const getCompanies = (params) => request.get('/companies', { params })
export const getAllCompanies = () => request.get('/companies/all')
export const getCompany = (id) => request.get(`/companies/${id}`)
export const createCompany = (data) => request.post('/companies', data)
export const updateCompany = (id, data) => request.put(`/companies/${id}`, data)
export const deleteCompany = (id) => request.delete(`/companies/${id}`)

export const getCustomers = (params) => request.get('/customers', { params })
export const getAllCustomers = () => request.get('/customers/all')
export const getCustomer = (id) => request.get(`/customers/${id}`)
export const createCustomer = (data) => request.post('/customers', data)
export const updateCustomer = (id, data) => request.put(`/customers/${id}`, data)
export const deleteCustomer = (id) => request.delete(`/customers/${id}`)

export const getRooms = (params) => request.get('/rooms', { params })
export const getRoom = (id) => request.get(`/rooms/${id}`)
export const createRoom = (data) => request.post('/rooms', data)
export const updateRoom = (id, data) => request.put(`/rooms/${id}`, data)
export const deleteRoom = (id) => request.delete(`/rooms/${id}`)

export const getRentals = (params) => request.get('/rentals', { params })
export const exportRentals = (params) => request.get('/rentals/export', { params, responseType: 'blob' })
export const getRental = (id) => request.get(`/rentals/${id}`)
export const getRoomRental = (roomId) => request.get(`/rentals/room/${roomId}`)
export const createRental = (roomId, data) => request.post(`/rentals/room/${roomId}`, data)
export const updateRental = (id, data) => request.put(`/rentals/${id}`, data)
export const modifyRental = (id, data) => request.put(`/rentals/${id}/modify`, data)
export const terminateRental = (id, data) => request.delete(`/rentals/${id}`, { data })

export const getGlobalBills = (params) => request.get('/bills/global', { params })
export const exportGlobalBills = (params) => request.get('/bills/global/export', { params, responseType: 'blob' })
export const getBills = (rentalId, params) => request.get(`/bills/rental/${rentalId}`, { params })
export const getBillStatistics = (rentalId) => request.get(`/bills/rental/${rentalId}/statistics`)
export const getBill = (id) => request.get(`/bills/${id}`)
export const createBill = (rentalId, data) => request.post(`/bills/rental/${rentalId}`, data)
export const updateBill = (id, data) => request.put(`/bills/${id}`, data)
export const calculatePenalty = (id) => request.get(`/bills/${id}/penalty`)

export const getRentalSummary = (keyword) => request.get('/reports/rental-summary', { params: { keyword } })
export const exportRentalSummary = (keyword) => request.get('/reports/rental-summary/export', { params: { keyword }, responseType: 'blob' })